markdown: kramdown
highlighter: rouge
sass:
  style: compressed

# gauges_id: 503c5af6613f5d0f19000027
# google_analytics_id: UA-50755011-1
# google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY

repository: https://github.com/mobb/documentation-test2
help_url: 

timezone: America/Los_Angeles

defaults:
  -
    scope:
      path: "_docs"
      type: "docs"
    values:
      layout: "docs"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "news_item"


collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /news/:year/:month/:day/:title/
    output: true
  tutorials:
    output: true

name: EDI testing proj documentation
description: Transform your plain text into static websites and blogs
url: https://mobb.github.io/documentation-test2

twitter:
  username: jekyllrb

logo: /img/logo-2x.png

plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - .gitignore
  - README.md

theme: jekyll-theme-cayman
